# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.




entries:
- title: Sidebar
  product: Plugin Tiles
  version:
  folders:


  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter


  - title: Getting Started
    output: web, pdf
    folderitems:
    

    - title: Plugins Background
      url: /plugins.html
      output: web, pdf

  
    - title: Guide to plugins development process
      url: /plugin_process.html
      output: web, pdf
          
  - title: Plugins catalogue
    output: web, pdf
    
  
