# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.




entries:
- title: Sidebar
  product: Core Tiles
  version:
  folders:


  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter


  - title: Core Tiles
    output: web, pdf
    folderitems:
    - title: Core Tiles
      url: /core_tiles_landing.html
      output: web, pdf

    - title: Patient Summary
      url: /Core_Tiles_PatientSummary.html
      output: web, pdf

    - title: Search
      url: /Core_Tiles_Search.html
      output: web, pdf

    - title: Multipatients View
      url: /Core_Tiles_Multipatients.html
      output: web, pdf

    - title: Charts
      url: /Core_Tiles_Charts.html
      output: web, pdf

    - title: Allergies
      url: /Core_Tiles_Allergies.html
      output: web, pdf

    - title: Contacts
      url: /Core_Tiles_Contacts.html
      output: web, pdf

    - title: Medictions
      url: /Core_Tiles_Medications.html
      output: web, pdf
