# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.




entries:
- title: Sidebar
  product: Plugin Tiles
  version:
  flagSidebar: mc
  folders:


  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

    folderitems:
    - title: Plugin Catalogue
      url: /plugin_tiles_landing.html
      output: web, pdf

    - title: Clinical Notes
      url: /Core_Tiles_ClinicalNotes.html
      output: web, pdf

    - title: Problems Diagnosis
      url: /Core_Tiles_Problems_Diagnosis.html
      output: web, pdf

    - title: Images
      url: /Core_Tiles_Images.html
      output: web, pdf

    - title: Documents
      url: /Core_Tiles_Documents.html
      output: web, pdf

    - title: MDT
      url: /Core_Tiles_MDT.html
      output: web, pdf

    - title: Orders
      url: /Core_Tiles_Orders.html
      output: web, pdf

    - title: Personal Notes
      url: /Core_Tiles_PersonalNotes.html
      output: web, pdf

    - title: Procedures
      url: /Core_Tiles_Procedures.html
      output: web, pdf

    - title: Referrals
      url: /Core_Tiles_Referrals.html
      output: web, pdf

    - title: Test Results
      url: /Core_Tiles_TestResults.html
      output: web, pdf

    - title: Vaccinations
      url: /Core_Tiles_Vaccinations.html
      output: web, pdf

    - title: Vitals
      url: /Core_Tiles_Vitals.html
      output: web, pdf

    - title: Clinical Statements
      url: /Core_Tiles_ClinicalStatements.html
      output: web, pdf

    - title: Events
      url: /Core_Tiles_Events.html
      output: web, pdf

    #- title: Example Page for Allergy
    #  url: /plugins.html
    # output: web, pdf
  
