# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.




entries:
- title: Sidebar
  product: PulseTile
  version: 1.0
  folders:


  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter


  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: PulseTile Home
      url: /p1_landing_page.html
      output: web


    - title: Core UI Project
      url: /coreuiproject.html
      output: web, pdf

    
  - title: Core Tiles
    output: web, pdf
  
    folderitems:    
    - title: Allergies
      url: /Core_Tiles_Allergies.html
      output: web, pdf  
   
    - title: Clinical Notes
      url: /Core_Tiles_ClinicalNotes.html
      output: web, pdf 
    
    - title: Contacts
      url: /Core_Tiles_Contacts.html
      output: web, pdf 
     
    - title: Medictions
      url: /Core_Tiles_Medications.html
      output: web, pdf 
       
    - title: Problems Diagnosis
      url: /Core_Tiles_Problems_Diagnosis.html
      output: web, pdf 
    
 
