# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Product 1 home
      url: /p1_landing_page.html
      output: web

    - title: Sample 1
      url: /p1_sample1.html
      output: web, pdf

    - title: Sample 2
      url: /p1_sample2.html
      output: web, pdf

    - title: Sample 3
      url: /p1_sample3.html
      output: web, pdf

  - title: Another heading
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf

    - title: Sample 5
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf

  - title: Background / Decision-making process
    output: web, pdf
    
    folderitems:
    - title: Initial Q&A
      url: /initial-QA.html
      output: web, pdf
      
    - title: Technologies
      url: /technologies.html
      output: web, pdf

    - title: Plugins
      url: /plugins.html
      output: web, pdf

    - title: Core UI Project
      url: /coreuiproject.html
      output: web, pdf

  - title: Plugins Development
    output: web, pdf

    folderitems:    
    - title: Guide to plugins development process
      url: /plugin_process.html
      output: web, pdf
      
  - title: API endpoints - JSON data
    output: web, pdf

    folderitems:    
    - title: JSON for Allergies module
      url: /JSON_Allergies.html
      output: web, pdf  
       
    - title: JSON for Contacts module
      url: /JSON_Contacts.html
      output: web, pdf   
   
    - title: JSON for MDT module
      url: /JSON_MDT.html
      output: web, pdf   
      
    - title: JSON for Medications module
      url: /JSON_Medication.html
      output: web, pdf   
      
    - title: JSON for Patients information
      url: /JSON_Patient_Information.html
      output: web, pdf   
      
    - title: JSON for Patient Lists
      url: /JSON_Patient_Lists.html
      output: web, pdf   
      
    - title: JSON Array Personal Notes
      url: /JSON_Personal_Notes.html
      output: web, pdf   
            
    - title: JSON for Procedures module
      url: /JSON_Procedures.html
      output: web, pdf   
            
    - title: JSON for Referrals module
      url: /JSON_Referrals.html
      output: web, pdf   
            
    - title: JSON for Test Results module
      url: /JSON_Results.html
      output: web, pdf   
            
    - title: JSON for Vitals module
      url: /JSON_Vitals.html
      output: web, pdf   
