# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.




entries:
- title: Sidebar
  product: Core UI Framework
  version:
  folders:


  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter


  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Background
      url: /p1_landing_page.html
      output: web


    - title: Licensing 
      url: /coreuiproject.html
      output: web, pdf

    
  - title: Core Tiles
    output: web, pdf
  
    folderitems:    
    - title: Allergies
      url: /Core_Tiles_Allergies.html
      output: web, pdf  
   
    - title: Clinical Notes
      url: /Core_Tiles_ClinicalNotes.html
      output: web, pdf 
    
    - title: Contacts
      url: /Core_Tiles_Contacts.html
      output: web, pdf 
     
    - title: Medictions
      url: /Core_Tiles_Medications.html
      output: web, pdf 
       
    - title: Problems Diagnosis
      url: /Core_Tiles_Problems_Diagnosis.html
      output: web, pdf 
    
 
    
  - title: API endpoints - JSON data
    output: web, pdf


    folderitems:    
    - title: JSON Array Allergies data
      url: /JSON_Allergies.html
      output: web, pdf  
       
    - title: JSON Array Contacts information
      url: /JSON_Contacts.html
      output: web, pdf   
   
    - title: JSON Array MDT
      url: /JSON_MDT.html
      output: web, pdf   
      
    - title: JSON Array Medications data
      url: /JSON_Medication.html
      output: web, pdf   
      
    - title: JSON Array Patient information
      url: /JSON_Patient_Information.html
      output: web, pdf   
      
    - title: JSON Array Patient list
      url: /JSON_Patient_Lists.html
      output: web, pdf   
      
    - title: JSON Array Personal Notes
      url: /JSON_Personal_Notes.html
      output: web, pdf   
            
    - title: JSON Array Procedures
      url: /JSON_Procedures.html
      output: web, pdf   
            
    - title: JSON Array Referrals
      url: /JSON_Referrals.html
      output: web, pdf   
            
    - title: JSON Array Test Results
      url: /JSON_Results.html
      output: web, pdf   
            
    - title: JSON array Vitals NEWS
      url: /JSON_Vitals.html
      output: web, pdf   
